### ISSUE TITLE
Selected date disappears when changing orientation

### ISSUE THREAD

**Issue by cherick04** [CVCalendar/CVCalendar#485]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of CVCalendar.
- [x] I have given my issue a non-generic title.

## Expected Behavior
Selected day should not disappear on orientation change.

## Current Behavior
After calendarView loads and the device is rotated once or twice (not consistent) the current selected day disappears. It shows up again when changing the date to a different date.

## Steps to Reproduce (for bugs)
1. Load calendarView (portrait) and select any date (10th in my case)
<img width="375" alt="screen shot 2017-10-12 at 4 52 36 pm" src="https://user-images.githubusercontent.com/17305697/31518676-0938260a-af6e-11e7-82ac-66dfa2075e0c.png">

2. Rotate device (calendarView doesn't resize properly on iPhones but we've always had that issue. That's another issue)
<img width="774" alt="screen shot 2017-10-12 at 4 52 54 pm" src="https://user-images.githubusercontent.com/17305697/31518697-175bf00e-af6e-11e7-8aed-8ba59393bb24.png">

3. You can rotate it back to portrait mode. Selected view is still gone
<img width="374" alt="screen shot 2017-10-12 at 4 53 12 pm" src="https://user-images.githubusercontent.com/17305697/31518795-5bda44ba-af6e-11e7-86ec-45a2a403229b.png">

4. In order to get day back, a different date needs to be selected (11th in my case)
<img width="375" alt="screen shot 2017-10-12 at 4 53 27 pm" src="https://user-images.githubusercontent.com/17305697/31518818-6c976eae-af6e-11e7-9314-9f8e2f4acce1.png">

## Context
If selected date doesn't disappear on the first rotation, try to rotate a second time.
The latest version that did not have this issue is 1.4.1

## Your Environment

* Version used (Cocoapods spec): 1.6.0
* Devices used: Simulator - iPhone SE, iPhone X, iPad Pro. Physical Device: iPad Mini 4th gen.

**Comment by Huddie** [comment]
+1

**Comment by KimPark89** [comment]
+1

**Comment by elsesiy** [comment]
@cherick04 I'll need some time to investigate, if someone already has a solution please submit a PR, thanks.

**Comment by RyanHop3** [comment]
Is there an easy workaround for the calendarView not resizing properly on iPhones? Have tried relentlessly but no luck.

**Comment by RyanHop3** [comment]
Any solution to this yet?

**Comment by elsesiy** [comment]
@RyanHop3 I haven't found the time, sorry. If you're able to contribute, please do so.

**Comment by elsesiy** [comment]
@cherick04 @RyanHop3 I think I found a fix, can you please test with this [branch](https://github.com/CVCalendar/CVCalendar/tree/bugfix/issue-485) and provide timely feedback. Thanks!

**Comment by KimPark89** [comment]
Unfortunately this is the result when I change the orientation:
![screen](https://user-images.githubusercontent.com/10373473/36073788-9901171a-0f36-11e8-8b46-6ce70073f69d.png)

**Comment by elsesiy** [comment]
@KimPark89 That's weird, I can't reproduce this with the demo. Can you provide a sample project please?

**Comment by cherick04** [comment]
@elsesiy, the same thing as @KimPark89 is occurring to me as well. Also, when I change back to original position, the selected day is still missing. See figures below:

1:
<img width="726" alt="1" src="https://user-images.githubusercontent.com/17305697/36102862-98d7937c-0fdb-11e8-8bdb-4bf8d44cadc3.png">

2:
<img width="495" alt="2" src="https://user-images.githubusercontent.com/17305697/36102889-b18d5a96-0fdb-11e8-94d2-b5f38b77aa8a.png">

3:
<img width="723" alt="3" src="https://user-images.githubusercontent.com/17305697/36102894-b7332a20-0fdb-11e8-952d-926093f97fe0.png">

**Comment by elsesiy** [comment]
@cherick04 Have you tried the demo? I can' reproduce this..

**Comment by KimPark89** [comment]
@elsesiy the problem is that I get the events with a request from a server and then I refresh the calendar.
This is my code (super simplified). In my real app I use an Alamofire request, while here I use a dispatch to simulate it, but the result is the same. 
N.B.: If you remove the call to presentedDateUpdated or the refreshPresentedMonth inside the dispatch, you resolve the multiple numbers problem, but the disappearance of the day circle when you change the orientation remains.

```
import UIKit
import CVCalendar

// Use a simple .xib with a CVCalendarMenuView and a CVCalendarView
class MyViewController: UIViewController, CVCalendarViewDelegate {
    
    @IBOutlet weak var menuView: CVCalendarMenuView!
    @IBOutlet weak var calendarView: CVCalendarView!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        presentedDateUpdated(CVDate(date: Date(), calendar: Calendar.current))
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        menuView.commitMenuViewUpdate()
        calendarView.commitCalendarViewUpdate()
    }
    
    /**
     * Download the events of the months, then refresh the calendar.
     */
    func getEventsOfMonth(_ date: Date) {
        
        // Dispatch to simulate the request to download the events
        DispatchQueue.global().async() {
            DispatchQueue.main.async() {
                
                // Refresh calendar after getting events
                self.calendarView.contentController.refreshPresentedMonth()
            }
        }
    }
    
    // MARK: - CVCalendarViewDelegate
    
    func presentationMode() -> CalendarMode {
        return .monthView
    }
    
    func firstWeekday() -> Weekday {
        return .monday
    }
    
    func presentedDateUpdated(_ date: CVDate) {
        if let date = date.convertedDate(calendar: Calendar.current) {
            getEventsOfMonth(date)
        }
    }

}
```

**Comment by elsesiy** [comment]
@KimPark89 @cherick04 You guys are testing with the branch I referenced yes? This behavior can be reproduced with the 1.6.1 but not with the branch I created.
You need to reference it from the Podfile like this:
`pod 'CVCalendar', :git => 'https://github.com/CVCalendar/CVCalendar.git', :branch => 'bugfix/issue-485'`

**Comment by KimPark89** [comment]
@elsesiy you right. Using the branch there's not the multiple numbers problem. But the circle day still disappears when changing orientation. 
Anyway this doesn't happen on the simplified version of my app (previous code) so I need to investigate more.

**Comment by elsesiy** [comment]
@KimPark89 @cherick04 Can you confirm this works as expected now?

**Comment by KimPark89** [comment]
@elsesiy I can confirm that this branch works better, but I still have some layout problems.
For example if I change orientation the dot event on the selected day disappears.
(Anyway I think that it doesn't really disappears, but it seems like the dot is moved down.)

**Comment by KimPark89** [comment]
@elsesiy I did some tests and these are the results:

RELEASE 1.6.0
- [ ] A) selected day circle disappears when changing orientation

RELEASE 1.6.1
- [ ] A) selected day circle disappears when changing orientation
- [ ] B) days labels are duplicated after changing orientation (right after calling refreshPresentedMonth())
- [ ] C) selected day label loses selected color after calling refreshPresentedMonth()

BRANCH (bugfix/issue-485):
- [x] A) selected day circle remains when changing orientation
- [x] B) days labels are not duplicated after changing orientation (right after calling refreshPresentedMonth())
- [ ] C) selected day label loses selected color after calling refreshPresentedMonth()
- [ ] D) selected day circle disappears when changing presentation mode (weekview/monthview)

A) (look at day 5)
<img width="848" alt="a" src="https://user-images.githubusercontent.com/10373473/37003226-a3d44426-20cc-11e8-8fcc-924f47df77eb.png">

B) 
<img width="562" alt="b" src="https://user-images.githubusercontent.com/10373473/37003229-a7586a1e-20cc-11e8-8a07-024f3050b09d.png">

C) (look at day 1)
<img width="839" alt="c" src="https://user-images.githubusercontent.com/10373473/37003233-a9db25ce-20cc-11e8-9672-1c08285de9f9.png">

D) (look at day 2)
<img width="845" alt="d" src="https://user-images.githubusercontent.com/10373473/37003238-ac68ed30-20cc-11e8-90f9-39ecfc333e54.png">

**Comment by elsesiy** [comment]
I just merged a fix (#507) that should solve C, D. Can you please re-test so we can get this finally fixed @KimPark89 ?

**Comment by elsesiy** [comment]
@KimPark89 that's what I thought. I'll look into this this weekend.

**Comment by cwinUser** [comment]
@elsesiy or @KimPark89  or @elsesiy 

I tried to use branch
 pod 'CVCalendar', :git => 'https://github.com/CVCalendar/CVCalendar.git', :branch => 'bugfix/issue-485' but is is giving me error while pod installation as below : 
[!] Error installing CVCalendar
[!] Failed to download 'CVCalendar'.

[!] Failed to load 'CVCalendar' podspec: 
[!] Invalid `CVCalendar.podspec` file: undefined method `swift_version=' for #<Pod::Specification name="CVCalendar">.


I am also facing same issue that while orientation selected day circle disappears.. so I tried to use above mentioned branch but its also not installing for me...

Please suggest solution need it urgent. :(

**Comment by elsesiy** [comment]
@KimPark89 A new release `1.6.2` is available, please re-test and report back, thanks!

**Comment by KimPark89** [comment]
@elsesiy the bug still persists on version 1.6.2.
When I change the device orientation, the selected date circle disappears.
I noticed that if I select a date before changing orientation it works (the selected date circle is correctly drawn), but if I let the selected date without changing it doesn't work (versions tested: 1.6.0, 1.6.1, 1.6.2).

For example, I open the calendar on 15 dec. If I change the orientation, the circle disappears.
But if I select a different date (16 dec for example), after changing orientation the circle appears correctly.
So if I always select a date before changing orientation, it always works.
